SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE
     , PRODUCT_ID
     , USER_ID
     , SALES_AMOUNT
FROM ONLINE_SALE
WHERE LEFT(SALES_DATE, 7) = '2022-03'

UNION

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE
     , PRODUCT_ID
     , NULL USER_ID
     , SALES_AMOUNT
FROM OFFLINE_SALE
WHERE LEFT(SALES_DATE, 7) = '2022-03'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;