WITH TMP(Y, M) AS
    (SELECT
        YEAR(DIFFERENTIATION_DATE) Y,
        MAX(SIZE_OF_COLONY) M
    FROM ECOLI_DATA
    GROUP BY Y)

SELECT
    YEAR(DIFFERENTIATION_DATE) YEAR,
    (TMP.M - SIZE_OF_COLONY) YEAR_DEV,
    ID
FROM ECOLI_DATA E
JOIN TMP
    ON YEAR(E.DIFFERENTIATION_DATE) = TMP.Y
ORDER BY YEAR, YEAR_DEV;